// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_login_5fprotocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_login_5fprotocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "login_enum.pb.h"
#include "login_struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_login_5fprotocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_login_5fprotocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[11]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_login_5fprotocol_2eproto;
namespace protocol {
class LoginClientCreateCharacter;
struct LoginClientCreateCharacterDefaultTypeInternal;
extern LoginClientCreateCharacterDefaultTypeInternal _LoginClientCreateCharacter_default_instance_;
class LoginClientDeleteCharacter;
struct LoginClientDeleteCharacterDefaultTypeInternal;
extern LoginClientDeleteCharacterDefaultTypeInternal _LoginClientDeleteCharacter_default_instance_;
class LoginClientLogin;
struct LoginClientLoginDefaultTypeInternal;
extern LoginClientLoginDefaultTypeInternal _LoginClientLogin_default_instance_;
class LoginClientRequestCharacterList;
struct LoginClientRequestCharacterListDefaultTypeInternal;
extern LoginClientRequestCharacterListDefaultTypeInternal _LoginClientRequestCharacterList_default_instance_;
class LoginClientSelectCharacter;
struct LoginClientSelectCharacterDefaultTypeInternal;
extern LoginClientSelectCharacterDefaultTypeInternal _LoginClientSelectCharacter_default_instance_;
class LoginServerCharSelectResult;
struct LoginServerCharSelectResultDefaultTypeInternal;
extern LoginServerCharSelectResultDefaultTypeInternal _LoginServerCharSelectResult_default_instance_;
class LoginServerCharacterList;
struct LoginServerCharacterListDefaultTypeInternal;
extern LoginServerCharacterListDefaultTypeInternal _LoginServerCharacterList_default_instance_;
class LoginServerChat;
struct LoginServerChatDefaultTypeInternal;
extern LoginServerChatDefaultTypeInternal _LoginServerChat_default_instance_;
class LoginServerCreateCharacter;
struct LoginServerCreateCharacterDefaultTypeInternal;
extern LoginServerCreateCharacterDefaultTypeInternal _LoginServerCreateCharacter_default_instance_;
class LoginServerDeleteCharacter;
struct LoginServerDeleteCharacterDefaultTypeInternal;
extern LoginServerDeleteCharacterDefaultTypeInternal _LoginServerDeleteCharacter_default_instance_;
class LoginServerLogin;
struct LoginServerLoginDefaultTypeInternal;
extern LoginServerLoginDefaultTypeInternal _LoginServerLogin_default_instance_;
}  // namespace protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::protocol::LoginClientCreateCharacter* Arena::CreateMaybeMessage<::protocol::LoginClientCreateCharacter>(Arena*);
template<> ::protocol::LoginClientDeleteCharacter* Arena::CreateMaybeMessage<::protocol::LoginClientDeleteCharacter>(Arena*);
template<> ::protocol::LoginClientLogin* Arena::CreateMaybeMessage<::protocol::LoginClientLogin>(Arena*);
template<> ::protocol::LoginClientRequestCharacterList* Arena::CreateMaybeMessage<::protocol::LoginClientRequestCharacterList>(Arena*);
template<> ::protocol::LoginClientSelectCharacter* Arena::CreateMaybeMessage<::protocol::LoginClientSelectCharacter>(Arena*);
template<> ::protocol::LoginServerCharSelectResult* Arena::CreateMaybeMessage<::protocol::LoginServerCharSelectResult>(Arena*);
template<> ::protocol::LoginServerCharacterList* Arena::CreateMaybeMessage<::protocol::LoginServerCharacterList>(Arena*);
template<> ::protocol::LoginServerChat* Arena::CreateMaybeMessage<::protocol::LoginServerChat>(Arena*);
template<> ::protocol::LoginServerCreateCharacter* Arena::CreateMaybeMessage<::protocol::LoginServerCreateCharacter>(Arena*);
template<> ::protocol::LoginServerDeleteCharacter* Arena::CreateMaybeMessage<::protocol::LoginServerDeleteCharacter>(Arena*);
template<> ::protocol::LoginServerLogin* Arena::CreateMaybeMessage<::protocol::LoginServerLogin>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protocol {

// ===================================================================

class LoginClientLogin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginClientLogin) */ {
 public:
  inline LoginClientLogin() : LoginClientLogin(nullptr) {}
  ~LoginClientLogin() override;
  explicit constexpr LoginClientLogin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginClientLogin(const LoginClientLogin& from);
  LoginClientLogin(LoginClientLogin&& from) noexcept
    : LoginClientLogin() {
    *this = ::std::move(from);
  }

  inline LoginClientLogin& operator=(const LoginClientLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginClientLogin& operator=(LoginClientLogin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginClientLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginClientLogin* internal_default_instance() {
    return reinterpret_cast<const LoginClientLogin*>(
               &_LoginClientLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LoginClientLogin& a, LoginClientLogin& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginClientLogin* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginClientLogin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginClientLogin* New() const final {
    return new LoginClientLogin();
  }

  LoginClientLogin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginClientLogin>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginClientLogin& from);
  void MergeFrom(const LoginClientLogin& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginClientLogin* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginClientLogin";
  }
  protected:
  explicit LoginClientLogin(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string username = 1;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:protocol.LoginClientLogin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class LoginServerLogin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginServerLogin) */ {
 public:
  inline LoginServerLogin() : LoginServerLogin(nullptr) {}
  ~LoginServerLogin() override;
  explicit constexpr LoginServerLogin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginServerLogin(const LoginServerLogin& from);
  LoginServerLogin(LoginServerLogin&& from) noexcept
    : LoginServerLogin() {
    *this = ::std::move(from);
  }

  inline LoginServerLogin& operator=(const LoginServerLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginServerLogin& operator=(LoginServerLogin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginServerLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginServerLogin* internal_default_instance() {
    return reinterpret_cast<const LoginServerLogin*>(
               &_LoginServerLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LoginServerLogin& a, LoginServerLogin& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginServerLogin* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginServerLogin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginServerLogin* New() const final {
    return new LoginServerLogin();
  }

  LoginServerLogin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginServerLogin>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginServerLogin& from);
  void MergeFrom(const LoginServerLogin& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginServerLogin* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginServerLogin";
  }
  protected:
  explicit LoginServerLogin(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // .protocol.LoginResult result = 1;
  void clear_result();
  ::protocol::LoginResult result() const;
  void set_result(::protocol::LoginResult value);
  private:
  ::protocol::LoginResult _internal_result() const;
  void _internal_set_result(::protocol::LoginResult value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.LoginServerLogin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class LoginClientRequestCharacterList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginClientRequestCharacterList) */ {
 public:
  inline LoginClientRequestCharacterList() : LoginClientRequestCharacterList(nullptr) {}
  ~LoginClientRequestCharacterList() override;
  explicit constexpr LoginClientRequestCharacterList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginClientRequestCharacterList(const LoginClientRequestCharacterList& from);
  LoginClientRequestCharacterList(LoginClientRequestCharacterList&& from) noexcept
    : LoginClientRequestCharacterList() {
    *this = ::std::move(from);
  }

  inline LoginClientRequestCharacterList& operator=(const LoginClientRequestCharacterList& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginClientRequestCharacterList& operator=(LoginClientRequestCharacterList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginClientRequestCharacterList& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginClientRequestCharacterList* internal_default_instance() {
    return reinterpret_cast<const LoginClientRequestCharacterList*>(
               &_LoginClientRequestCharacterList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LoginClientRequestCharacterList& a, LoginClientRequestCharacterList& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginClientRequestCharacterList* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginClientRequestCharacterList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginClientRequestCharacterList* New() const final {
    return new LoginClientRequestCharacterList();
  }

  LoginClientRequestCharacterList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginClientRequestCharacterList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginClientRequestCharacterList& from);
  void MergeFrom(const LoginClientRequestCharacterList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginClientRequestCharacterList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginClientRequestCharacterList";
  }
  protected:
  explicit LoginClientRequestCharacterList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:protocol.LoginClientRequestCharacterList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class LoginServerCharacterList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginServerCharacterList) */ {
 public:
  inline LoginServerCharacterList() : LoginServerCharacterList(nullptr) {}
  ~LoginServerCharacterList() override;
  explicit constexpr LoginServerCharacterList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginServerCharacterList(const LoginServerCharacterList& from);
  LoginServerCharacterList(LoginServerCharacterList&& from) noexcept
    : LoginServerCharacterList() {
    *this = ::std::move(from);
  }

  inline LoginServerCharacterList& operator=(const LoginServerCharacterList& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginServerCharacterList& operator=(LoginServerCharacterList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginServerCharacterList& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginServerCharacterList* internal_default_instance() {
    return reinterpret_cast<const LoginServerCharacterList*>(
               &_LoginServerCharacterList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(LoginServerCharacterList& a, LoginServerCharacterList& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginServerCharacterList* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginServerCharacterList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginServerCharacterList* New() const final {
    return new LoginServerCharacterList();
  }

  LoginServerCharacterList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginServerCharacterList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginServerCharacterList& from);
  void MergeFrom(const LoginServerCharacterList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginServerCharacterList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginServerCharacterList";
  }
  protected:
  explicit LoginServerCharacterList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCharactersFieldNumber = 1,
  };
  // repeated .protocol.LoginCharacter characters = 1;
  int characters_size() const;
  private:
  int _internal_characters_size() const;
  public:
  void clear_characters();
  ::protocol::LoginCharacter* mutable_characters(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::LoginCharacter >*
      mutable_characters();
  private:
  const ::protocol::LoginCharacter& _internal_characters(int index) const;
  ::protocol::LoginCharacter* _internal_add_characters();
  public:
  const ::protocol::LoginCharacter& characters(int index) const;
  ::protocol::LoginCharacter* add_characters();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::LoginCharacter >&
      characters() const;

  // @@protoc_insertion_point(class_scope:protocol.LoginServerCharacterList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::LoginCharacter > characters_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class LoginClientSelectCharacter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginClientSelectCharacter) */ {
 public:
  inline LoginClientSelectCharacter() : LoginClientSelectCharacter(nullptr) {}
  ~LoginClientSelectCharacter() override;
  explicit constexpr LoginClientSelectCharacter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginClientSelectCharacter(const LoginClientSelectCharacter& from);
  LoginClientSelectCharacter(LoginClientSelectCharacter&& from) noexcept
    : LoginClientSelectCharacter() {
    *this = ::std::move(from);
  }

  inline LoginClientSelectCharacter& operator=(const LoginClientSelectCharacter& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginClientSelectCharacter& operator=(LoginClientSelectCharacter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginClientSelectCharacter& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginClientSelectCharacter* internal_default_instance() {
    return reinterpret_cast<const LoginClientSelectCharacter*>(
               &_LoginClientSelectCharacter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(LoginClientSelectCharacter& a, LoginClientSelectCharacter& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginClientSelectCharacter* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginClientSelectCharacter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginClientSelectCharacter* New() const final {
    return new LoginClientSelectCharacter();
  }

  LoginClientSelectCharacter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginClientSelectCharacter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginClientSelectCharacter& from);
  void MergeFrom(const LoginClientSelectCharacter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginClientSelectCharacter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginClientSelectCharacter";
  }
  protected:
  explicit LoginClientSelectCharacter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCharacterIdFieldNumber = 1,
  };
  // int32 character_id = 1;
  void clear_character_id();
  ::PROTOBUF_NAMESPACE_ID::int32 character_id() const;
  void set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_character_id() const;
  void _internal_set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.LoginClientSelectCharacter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 character_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class LoginClientDeleteCharacter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginClientDeleteCharacter) */ {
 public:
  inline LoginClientDeleteCharacter() : LoginClientDeleteCharacter(nullptr) {}
  ~LoginClientDeleteCharacter() override;
  explicit constexpr LoginClientDeleteCharacter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginClientDeleteCharacter(const LoginClientDeleteCharacter& from);
  LoginClientDeleteCharacter(LoginClientDeleteCharacter&& from) noexcept
    : LoginClientDeleteCharacter() {
    *this = ::std::move(from);
  }

  inline LoginClientDeleteCharacter& operator=(const LoginClientDeleteCharacter& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginClientDeleteCharacter& operator=(LoginClientDeleteCharacter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginClientDeleteCharacter& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginClientDeleteCharacter* internal_default_instance() {
    return reinterpret_cast<const LoginClientDeleteCharacter*>(
               &_LoginClientDeleteCharacter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(LoginClientDeleteCharacter& a, LoginClientDeleteCharacter& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginClientDeleteCharacter* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginClientDeleteCharacter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginClientDeleteCharacter* New() const final {
    return new LoginClientDeleteCharacter();
  }

  LoginClientDeleteCharacter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginClientDeleteCharacter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginClientDeleteCharacter& from);
  void MergeFrom(const LoginClientDeleteCharacter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginClientDeleteCharacter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginClientDeleteCharacter";
  }
  protected:
  explicit LoginClientDeleteCharacter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCharacterIdFieldNumber = 1,
  };
  // int32 character_id = 1;
  void clear_character_id();
  ::PROTOBUF_NAMESPACE_ID::int32 character_id() const;
  void set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_character_id() const;
  void _internal_set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.LoginClientDeleteCharacter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 character_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class LoginServerDeleteCharacter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginServerDeleteCharacter) */ {
 public:
  inline LoginServerDeleteCharacter() : LoginServerDeleteCharacter(nullptr) {}
  ~LoginServerDeleteCharacter() override;
  explicit constexpr LoginServerDeleteCharacter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginServerDeleteCharacter(const LoginServerDeleteCharacter& from);
  LoginServerDeleteCharacter(LoginServerDeleteCharacter&& from) noexcept
    : LoginServerDeleteCharacter() {
    *this = ::std::move(from);
  }

  inline LoginServerDeleteCharacter& operator=(const LoginServerDeleteCharacter& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginServerDeleteCharacter& operator=(LoginServerDeleteCharacter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginServerDeleteCharacter& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginServerDeleteCharacter* internal_default_instance() {
    return reinterpret_cast<const LoginServerDeleteCharacter*>(
               &_LoginServerDeleteCharacter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(LoginServerDeleteCharacter& a, LoginServerDeleteCharacter& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginServerDeleteCharacter* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginServerDeleteCharacter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginServerDeleteCharacter* New() const final {
    return new LoginServerDeleteCharacter();
  }

  LoginServerDeleteCharacter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginServerDeleteCharacter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginServerDeleteCharacter& from);
  void MergeFrom(const LoginServerDeleteCharacter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginServerDeleteCharacter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginServerDeleteCharacter";
  }
  protected:
  explicit LoginServerDeleteCharacter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
    kCharacterIdFieldNumber = 2,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 character_id = 2;
  void clear_character_id();
  ::PROTOBUF_NAMESPACE_ID::int32 character_id() const;
  void set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_character_id() const;
  void _internal_set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.LoginServerDeleteCharacter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool success_;
  ::PROTOBUF_NAMESPACE_ID::int32 character_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class LoginClientCreateCharacter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginClientCreateCharacter) */ {
 public:
  inline LoginClientCreateCharacter() : LoginClientCreateCharacter(nullptr) {}
  ~LoginClientCreateCharacter() override;
  explicit constexpr LoginClientCreateCharacter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginClientCreateCharacter(const LoginClientCreateCharacter& from);
  LoginClientCreateCharacter(LoginClientCreateCharacter&& from) noexcept
    : LoginClientCreateCharacter() {
    *this = ::std::move(from);
  }

  inline LoginClientCreateCharacter& operator=(const LoginClientCreateCharacter& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginClientCreateCharacter& operator=(LoginClientCreateCharacter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginClientCreateCharacter& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginClientCreateCharacter* internal_default_instance() {
    return reinterpret_cast<const LoginClientCreateCharacter*>(
               &_LoginClientCreateCharacter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(LoginClientCreateCharacter& a, LoginClientCreateCharacter& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginClientCreateCharacter* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginClientCreateCharacter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginClientCreateCharacter* New() const final {
    return new LoginClientCreateCharacter();
  }

  LoginClientCreateCharacter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginClientCreateCharacter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginClientCreateCharacter& from);
  void MergeFrom(const LoginClientCreateCharacter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginClientCreateCharacter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginClientCreateCharacter";
  }
  protected:
  explicit LoginClientCreateCharacter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 type = 2;
  void clear_type();
  ::PROTOBUF_NAMESPACE_ID::int32 type() const;
  void set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_type() const;
  void _internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.LoginClientCreateCharacter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::int32 type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class LoginServerCreateCharacter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginServerCreateCharacter) */ {
 public:
  inline LoginServerCreateCharacter() : LoginServerCreateCharacter(nullptr) {}
  ~LoginServerCreateCharacter() override;
  explicit constexpr LoginServerCreateCharacter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginServerCreateCharacter(const LoginServerCreateCharacter& from);
  LoginServerCreateCharacter(LoginServerCreateCharacter&& from) noexcept
    : LoginServerCreateCharacter() {
    *this = ::std::move(from);
  }

  inline LoginServerCreateCharacter& operator=(const LoginServerCreateCharacter& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginServerCreateCharacter& operator=(LoginServerCreateCharacter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginServerCreateCharacter& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginServerCreateCharacter* internal_default_instance() {
    return reinterpret_cast<const LoginServerCreateCharacter*>(
               &_LoginServerCreateCharacter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(LoginServerCreateCharacter& a, LoginServerCreateCharacter& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginServerCreateCharacter* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginServerCreateCharacter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginServerCreateCharacter* New() const final {
    return new LoginServerCreateCharacter();
  }

  LoginServerCreateCharacter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginServerCreateCharacter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginServerCreateCharacter& from);
  void MergeFrom(const LoginServerCreateCharacter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginServerCreateCharacter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginServerCreateCharacter";
  }
  protected:
  explicit LoginServerCreateCharacter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCharacterFieldNumber = 2,
    kResultFieldNumber = 1,
  };
  // optional .protocol.LoginCharacter character = 2;
  bool has_character() const;
  private:
  bool _internal_has_character() const;
  public:
  void clear_character();
  const ::protocol::LoginCharacter& character() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::protocol::LoginCharacter* release_character();
  ::protocol::LoginCharacter* mutable_character();
  void set_allocated_character(::protocol::LoginCharacter* character);
  private:
  const ::protocol::LoginCharacter& _internal_character() const;
  ::protocol::LoginCharacter* _internal_mutable_character();
  public:
  void unsafe_arena_set_allocated_character(
      ::protocol::LoginCharacter* character);
  ::protocol::LoginCharacter* unsafe_arena_release_character();

  // .protocol.CreateCharResult result = 1;
  void clear_result();
  ::protocol::CreateCharResult result() const;
  void set_result(::protocol::CreateCharResult value);
  private:
  ::protocol::CreateCharResult _internal_result() const;
  void _internal_set_result(::protocol::CreateCharResult value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.LoginServerCreateCharacter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::protocol::LoginCharacter* character_;
  int result_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class LoginServerCharSelectResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginServerCharSelectResult) */ {
 public:
  inline LoginServerCharSelectResult() : LoginServerCharSelectResult(nullptr) {}
  ~LoginServerCharSelectResult() override;
  explicit constexpr LoginServerCharSelectResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginServerCharSelectResult(const LoginServerCharSelectResult& from);
  LoginServerCharSelectResult(LoginServerCharSelectResult&& from) noexcept
    : LoginServerCharSelectResult() {
    *this = ::std::move(from);
  }

  inline LoginServerCharSelectResult& operator=(const LoginServerCharSelectResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginServerCharSelectResult& operator=(LoginServerCharSelectResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginServerCharSelectResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginServerCharSelectResult* internal_default_instance() {
    return reinterpret_cast<const LoginServerCharSelectResult*>(
               &_LoginServerCharSelectResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(LoginServerCharSelectResult& a, LoginServerCharSelectResult& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginServerCharSelectResult* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginServerCharSelectResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginServerCharSelectResult* New() const final {
    return new LoginServerCharSelectResult();
  }

  LoginServerCharSelectResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginServerCharSelectResult>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginServerCharSelectResult& from);
  void MergeFrom(const LoginServerCharSelectResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginServerCharSelectResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginServerCharSelectResult";
  }
  protected:
  explicit LoginServerCharSelectResult(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 2,
    kResultFieldNumber = 1,
    kPortFieldNumber = 3,
  };
  // optional string ip = 2;
  bool has_ip() const;
  private:
  bool _internal_has_ip() const;
  public:
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // .protocol.SelectCharResult result = 1;
  void clear_result();
  ::protocol::SelectCharResult result() const;
  void set_result(::protocol::SelectCharResult value);
  private:
  ::protocol::SelectCharResult _internal_result() const;
  void _internal_set_result(::protocol::SelectCharResult value);
  public:

  // optional int32 port = 3;
  bool has_port() const;
  private:
  bool _internal_has_port() const;
  public:
  void clear_port();
  ::PROTOBUF_NAMESPACE_ID::int32 port() const;
  void set_port(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_port() const;
  void _internal_set_port(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.LoginServerCharSelectResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
  int result_;
  ::PROTOBUF_NAMESPACE_ID::int32 port_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class LoginServerChat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.LoginServerChat) */ {
 public:
  inline LoginServerChat() : LoginServerChat(nullptr) {}
  ~LoginServerChat() override;
  explicit constexpr LoginServerChat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginServerChat(const LoginServerChat& from);
  LoginServerChat(LoginServerChat&& from) noexcept
    : LoginServerChat() {
    *this = ::std::move(from);
  }

  inline LoginServerChat& operator=(const LoginServerChat& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginServerChat& operator=(LoginServerChat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginServerChat& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginServerChat* internal_default_instance() {
    return reinterpret_cast<const LoginServerChat*>(
               &_LoginServerChat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(LoginServerChat& a, LoginServerChat& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginServerChat* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginServerChat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginServerChat* New() const final {
    return new LoginServerChat();
  }

  LoginServerChat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginServerChat>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginServerChat& from);
  void MergeFrom(const LoginServerChat& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginServerChat* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.LoginServerChat";
  }
  protected:
  explicit LoginServerChat(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:protocol.LoginServerChat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fprotocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LoginClientLogin

// string username = 1;
inline void LoginClientLogin::clear_username() {
  username_.ClearToEmpty();
}
inline const std::string& LoginClientLogin::username() const {
  // @@protoc_insertion_point(field_get:protocol.LoginClientLogin.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginClientLogin::set_username(ArgT0&& arg0, ArgT... args) {
 
 username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol.LoginClientLogin.username)
}
inline std::string* LoginClientLogin::mutable_username() {
  // @@protoc_insertion_point(field_mutable:protocol.LoginClientLogin.username)
  return _internal_mutable_username();
}
inline const std::string& LoginClientLogin::_internal_username() const {
  return username_.Get();
}
inline void LoginClientLogin::_internal_set_username(const std::string& value) {
  
  username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LoginClientLogin::_internal_mutable_username() {
  
  return username_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LoginClientLogin::release_username() {
  // @@protoc_insertion_point(field_release:protocol.LoginClientLogin.username)
  return username_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LoginClientLogin::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  username_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), username,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:protocol.LoginClientLogin.username)
}

// string password = 2;
inline void LoginClientLogin::clear_password() {
  password_.ClearToEmpty();
}
inline const std::string& LoginClientLogin::password() const {
  // @@protoc_insertion_point(field_get:protocol.LoginClientLogin.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginClientLogin::set_password(ArgT0&& arg0, ArgT... args) {
 
 password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol.LoginClientLogin.password)
}
inline std::string* LoginClientLogin::mutable_password() {
  // @@protoc_insertion_point(field_mutable:protocol.LoginClientLogin.password)
  return _internal_mutable_password();
}
inline const std::string& LoginClientLogin::_internal_password() const {
  return password_.Get();
}
inline void LoginClientLogin::_internal_set_password(const std::string& value) {
  
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LoginClientLogin::_internal_mutable_password() {
  
  return password_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LoginClientLogin::release_password() {
  // @@protoc_insertion_point(field_release:protocol.LoginClientLogin.password)
  return password_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LoginClientLogin::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:protocol.LoginClientLogin.password)
}

// -------------------------------------------------------------------

// LoginServerLogin

// .protocol.LoginResult result = 1;
inline void LoginServerLogin::clear_result() {
  result_ = 0;
}
inline ::protocol::LoginResult LoginServerLogin::_internal_result() const {
  return static_cast< ::protocol::LoginResult >(result_);
}
inline ::protocol::LoginResult LoginServerLogin::result() const {
  // @@protoc_insertion_point(field_get:protocol.LoginServerLogin.result)
  return _internal_result();
}
inline void LoginServerLogin::_internal_set_result(::protocol::LoginResult value) {
  
  result_ = value;
}
inline void LoginServerLogin::set_result(::protocol::LoginResult value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:protocol.LoginServerLogin.result)
}

// -------------------------------------------------------------------

// LoginClientRequestCharacterList

// -------------------------------------------------------------------

// LoginServerCharacterList

// repeated .protocol.LoginCharacter characters = 1;
inline int LoginServerCharacterList::_internal_characters_size() const {
  return characters_.size();
}
inline int LoginServerCharacterList::characters_size() const {
  return _internal_characters_size();
}
inline ::protocol::LoginCharacter* LoginServerCharacterList::mutable_characters(int index) {
  // @@protoc_insertion_point(field_mutable:protocol.LoginServerCharacterList.characters)
  return characters_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::LoginCharacter >*
LoginServerCharacterList::mutable_characters() {
  // @@protoc_insertion_point(field_mutable_list:protocol.LoginServerCharacterList.characters)
  return &characters_;
}
inline const ::protocol::LoginCharacter& LoginServerCharacterList::_internal_characters(int index) const {
  return characters_.Get(index);
}
inline const ::protocol::LoginCharacter& LoginServerCharacterList::characters(int index) const {
  // @@protoc_insertion_point(field_get:protocol.LoginServerCharacterList.characters)
  return _internal_characters(index);
}
inline ::protocol::LoginCharacter* LoginServerCharacterList::_internal_add_characters() {
  return characters_.Add();
}
inline ::protocol::LoginCharacter* LoginServerCharacterList::add_characters() {
  // @@protoc_insertion_point(field_add:protocol.LoginServerCharacterList.characters)
  return _internal_add_characters();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::LoginCharacter >&
LoginServerCharacterList::characters() const {
  // @@protoc_insertion_point(field_list:protocol.LoginServerCharacterList.characters)
  return characters_;
}

// -------------------------------------------------------------------

// LoginClientSelectCharacter

// int32 character_id = 1;
inline void LoginClientSelectCharacter::clear_character_id() {
  character_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoginClientSelectCharacter::_internal_character_id() const {
  return character_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoginClientSelectCharacter::character_id() const {
  // @@protoc_insertion_point(field_get:protocol.LoginClientSelectCharacter.character_id)
  return _internal_character_id();
}
inline void LoginClientSelectCharacter::_internal_set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  character_id_ = value;
}
inline void LoginClientSelectCharacter::set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_character_id(value);
  // @@protoc_insertion_point(field_set:protocol.LoginClientSelectCharacter.character_id)
}

// -------------------------------------------------------------------

// LoginClientDeleteCharacter

// int32 character_id = 1;
inline void LoginClientDeleteCharacter::clear_character_id() {
  character_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoginClientDeleteCharacter::_internal_character_id() const {
  return character_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoginClientDeleteCharacter::character_id() const {
  // @@protoc_insertion_point(field_get:protocol.LoginClientDeleteCharacter.character_id)
  return _internal_character_id();
}
inline void LoginClientDeleteCharacter::_internal_set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  character_id_ = value;
}
inline void LoginClientDeleteCharacter::set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_character_id(value);
  // @@protoc_insertion_point(field_set:protocol.LoginClientDeleteCharacter.character_id)
}

// -------------------------------------------------------------------

// LoginServerDeleteCharacter

// bool success = 1;
inline void LoginServerDeleteCharacter::clear_success() {
  success_ = false;
}
inline bool LoginServerDeleteCharacter::_internal_success() const {
  return success_;
}
inline bool LoginServerDeleteCharacter::success() const {
  // @@protoc_insertion_point(field_get:protocol.LoginServerDeleteCharacter.success)
  return _internal_success();
}
inline void LoginServerDeleteCharacter::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void LoginServerDeleteCharacter::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:protocol.LoginServerDeleteCharacter.success)
}

// int32 character_id = 2;
inline void LoginServerDeleteCharacter::clear_character_id() {
  character_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoginServerDeleteCharacter::_internal_character_id() const {
  return character_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoginServerDeleteCharacter::character_id() const {
  // @@protoc_insertion_point(field_get:protocol.LoginServerDeleteCharacter.character_id)
  return _internal_character_id();
}
inline void LoginServerDeleteCharacter::_internal_set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  character_id_ = value;
}
inline void LoginServerDeleteCharacter::set_character_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_character_id(value);
  // @@protoc_insertion_point(field_set:protocol.LoginServerDeleteCharacter.character_id)
}

// -------------------------------------------------------------------

// LoginClientCreateCharacter

// string name = 1;
inline void LoginClientCreateCharacter::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& LoginClientCreateCharacter::name() const {
  // @@protoc_insertion_point(field_get:protocol.LoginClientCreateCharacter.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginClientCreateCharacter::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol.LoginClientCreateCharacter.name)
}
inline std::string* LoginClientCreateCharacter::mutable_name() {
  // @@protoc_insertion_point(field_mutable:protocol.LoginClientCreateCharacter.name)
  return _internal_mutable_name();
}
inline const std::string& LoginClientCreateCharacter::_internal_name() const {
  return name_.Get();
}
inline void LoginClientCreateCharacter::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LoginClientCreateCharacter::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LoginClientCreateCharacter::release_name() {
  // @@protoc_insertion_point(field_release:protocol.LoginClientCreateCharacter.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LoginClientCreateCharacter::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:protocol.LoginClientCreateCharacter.name)
}

// int32 type = 2;
inline void LoginClientCreateCharacter::clear_type() {
  type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoginClientCreateCharacter::_internal_type() const {
  return type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoginClientCreateCharacter::type() const {
  // @@protoc_insertion_point(field_get:protocol.LoginClientCreateCharacter.type)
  return _internal_type();
}
inline void LoginClientCreateCharacter::_internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  type_ = value;
}
inline void LoginClientCreateCharacter::set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:protocol.LoginClientCreateCharacter.type)
}

// -------------------------------------------------------------------

// LoginServerCreateCharacter

// .protocol.CreateCharResult result = 1;
inline void LoginServerCreateCharacter::clear_result() {
  result_ = 0;
}
inline ::protocol::CreateCharResult LoginServerCreateCharacter::_internal_result() const {
  return static_cast< ::protocol::CreateCharResult >(result_);
}
inline ::protocol::CreateCharResult LoginServerCreateCharacter::result() const {
  // @@protoc_insertion_point(field_get:protocol.LoginServerCreateCharacter.result)
  return _internal_result();
}
inline void LoginServerCreateCharacter::_internal_set_result(::protocol::CreateCharResult value) {
  
  result_ = value;
}
inline void LoginServerCreateCharacter::set_result(::protocol::CreateCharResult value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:protocol.LoginServerCreateCharacter.result)
}

// optional .protocol.LoginCharacter character = 2;
inline bool LoginServerCreateCharacter::_internal_has_character() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || character_ != nullptr);
  return value;
}
inline bool LoginServerCreateCharacter::has_character() const {
  return _internal_has_character();
}
inline const ::protocol::LoginCharacter& LoginServerCreateCharacter::_internal_character() const {
  const ::protocol::LoginCharacter* p = character_;
  return p != nullptr ? *p : reinterpret_cast<const ::protocol::LoginCharacter&>(
      ::protocol::_LoginCharacter_default_instance_);
}
inline const ::protocol::LoginCharacter& LoginServerCreateCharacter::character() const {
  // @@protoc_insertion_point(field_get:protocol.LoginServerCreateCharacter.character)
  return _internal_character();
}
inline void LoginServerCreateCharacter::unsafe_arena_set_allocated_character(
    ::protocol::LoginCharacter* character) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(character_);
  }
  character_ = character;
  if (character) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.LoginServerCreateCharacter.character)
}
inline ::protocol::LoginCharacter* LoginServerCreateCharacter::release_character() {
  _has_bits_[0] &= ~0x00000001u;
  ::protocol::LoginCharacter* temp = character_;
  character_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::protocol::LoginCharacter* LoginServerCreateCharacter::unsafe_arena_release_character() {
  // @@protoc_insertion_point(field_release:protocol.LoginServerCreateCharacter.character)
  _has_bits_[0] &= ~0x00000001u;
  ::protocol::LoginCharacter* temp = character_;
  character_ = nullptr;
  return temp;
}
inline ::protocol::LoginCharacter* LoginServerCreateCharacter::_internal_mutable_character() {
  _has_bits_[0] |= 0x00000001u;
  if (character_ == nullptr) {
    auto* p = CreateMaybeMessage<::protocol::LoginCharacter>(GetArenaForAllocation());
    character_ = p;
  }
  return character_;
}
inline ::protocol::LoginCharacter* LoginServerCreateCharacter::mutable_character() {
  // @@protoc_insertion_point(field_mutable:protocol.LoginServerCreateCharacter.character)
  return _internal_mutable_character();
}
inline void LoginServerCreateCharacter::set_allocated_character(::protocol::LoginCharacter* character) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(character_);
  }
  if (character) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(character));
    if (message_arena != submessage_arena) {
      character = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, character, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  character_ = character;
  // @@protoc_insertion_point(field_set_allocated:protocol.LoginServerCreateCharacter.character)
}

// -------------------------------------------------------------------

// LoginServerCharSelectResult

// .protocol.SelectCharResult result = 1;
inline void LoginServerCharSelectResult::clear_result() {
  result_ = 0;
}
inline ::protocol::SelectCharResult LoginServerCharSelectResult::_internal_result() const {
  return static_cast< ::protocol::SelectCharResult >(result_);
}
inline ::protocol::SelectCharResult LoginServerCharSelectResult::result() const {
  // @@protoc_insertion_point(field_get:protocol.LoginServerCharSelectResult.result)
  return _internal_result();
}
inline void LoginServerCharSelectResult::_internal_set_result(::protocol::SelectCharResult value) {
  
  result_ = value;
}
inline void LoginServerCharSelectResult::set_result(::protocol::SelectCharResult value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:protocol.LoginServerCharSelectResult.result)
}

// optional string ip = 2;
inline bool LoginServerCharSelectResult::_internal_has_ip() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LoginServerCharSelectResult::has_ip() const {
  return _internal_has_ip();
}
inline void LoginServerCharSelectResult::clear_ip() {
  ip_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& LoginServerCharSelectResult::ip() const {
  // @@protoc_insertion_point(field_get:protocol.LoginServerCharSelectResult.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginServerCharSelectResult::set_ip(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol.LoginServerCharSelectResult.ip)
}
inline std::string* LoginServerCharSelectResult::mutable_ip() {
  // @@protoc_insertion_point(field_mutable:protocol.LoginServerCharSelectResult.ip)
  return _internal_mutable_ip();
}
inline const std::string& LoginServerCharSelectResult::_internal_ip() const {
  return ip_.Get();
}
inline void LoginServerCharSelectResult::_internal_set_ip(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LoginServerCharSelectResult::_internal_mutable_ip() {
  _has_bits_[0] |= 0x00000001u;
  return ip_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LoginServerCharSelectResult::release_ip() {
  // @@protoc_insertion_point(field_release:protocol.LoginServerCharSelectResult.ip)
  if (!_internal_has_ip()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return ip_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LoginServerCharSelectResult::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  ip_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ip,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:protocol.LoginServerCharSelectResult.ip)
}

// optional int32 port = 3;
inline bool LoginServerCharSelectResult::_internal_has_port() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool LoginServerCharSelectResult::has_port() const {
  return _internal_has_port();
}
inline void LoginServerCharSelectResult::clear_port() {
  port_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoginServerCharSelectResult::_internal_port() const {
  return port_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoginServerCharSelectResult::port() const {
  // @@protoc_insertion_point(field_get:protocol.LoginServerCharSelectResult.port)
  return _internal_port();
}
inline void LoginServerCharSelectResult::_internal_set_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  port_ = value;
}
inline void LoginServerCharSelectResult::set_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:protocol.LoginServerCharSelectResult.port)
}

// -------------------------------------------------------------------

// LoginServerChat

// string message = 1;
inline void LoginServerChat::clear_message() {
  message_.ClearToEmpty();
}
inline const std::string& LoginServerChat::message() const {
  // @@protoc_insertion_point(field_get:protocol.LoginServerChat.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginServerChat::set_message(ArgT0&& arg0, ArgT... args) {
 
 message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol.LoginServerChat.message)
}
inline std::string* LoginServerChat::mutable_message() {
  // @@protoc_insertion_point(field_mutable:protocol.LoginServerChat.message)
  return _internal_mutable_message();
}
inline const std::string& LoginServerChat::_internal_message() const {
  return message_.Get();
}
inline void LoginServerChat::_internal_set_message(const std::string& value) {
  
  message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LoginServerChat::_internal_mutable_message() {
  
  return message_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LoginServerChat::release_message() {
  // @@protoc_insertion_point(field_release:protocol.LoginServerChat.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LoginServerChat::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:protocol.LoginServerChat.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_login_5fprotocol_2eproto
